# PATH SETTINGS
# -------------
# Use forward slashes (/) or double backslashes (\\) for Windows paths

# Parent folder containing subfolders for each set of videos (e.g., T60253002_A)
input_directory: "C:\\Users\\matt.grossi\\Documents\\gh-repos\\PEM-ACRF-SEFIS-VideoPreProcessing\\_videos"

# Where the stitched videos will be saved
output_directory: "C:\\Users\\matt.grossi\\Documents\\gh-repos\\PEM-ACRF-SEFIS-VideoPreProcessing\\_videos"

# Path to the "time-on-bottom" CSV file and column names (adjust as needed)
csv_path: "C:\\Users\\matt.grossi\\Documents\\gh-repos\\PEM-ACRF-SEFIS-VideoPreProcessing\\_videos\\SEFIS test vids.csv"
col_foldername: "foldername"
col_timebottom: "timebottom"


# PROCESSING SETTINGS
# -------------------
# These settings control how the videos are processed. Adjust as needed.

# Reprocess mode: If true, existing stitched videos will be overwritten.
# Otherwise, skips folders where the output file already exists.
reprocess: false

# Diagnostic mode: If true, prints the video cut times to the console and
# embeds a timestamp into the video.
diagnostic_mode: false

# Clear log: If true, clears the log file at the start of each run. Otherwise,
# appends to the existing log. Defaults to false.
clear_log: false

# Whether to use GPU acceleration (requires compatible ffmpeg build and GPU)
use_gpu: true


# VIDEO PROCESSING UTILITIES (OPTIONAL)
# -------------------------------------
# These should not need to be changed unless you have multiple copies of FFmpeg
# installed and want to use a specific version.
ffmpeg_path: "ffmpeg/bin/ffmpeg.exe"
ffprobe_path: "ffmpeg/bin/ffprobe.exe"