# ----- PATH SETTINGS -----
# Use forward slashes (/) or double backslashes (\\) for Windows paths

# Parent folder containing subfolders for each set of videos (e.g., T60253002_A)
input_directory: "N:\\VIDEO_DATA\\2025_SEFIS_STITCHING_CLIPPING"

# Where the stitched videos will be saved
output_directory: "N:\\VIDEO_DATA\\2025_SEFIS_STITCHING_CLIPPING"

# Path to the "time-on-bottom" CSV file and column names (adjust as needed)
csv_path: "N:\\VIDEO_DATA\\2025_SEFIS_STITCHING_CLIPPING\\SEFIS test vids.csv"
col_foldername: "foldername"
col_timebottom: "timebottom"

# Path to log file where processing details and errors will be recorded
log_file: "N:\\VIDEO_DATA\\2025_SEFIS_STITCHING_CLIPPING\\processing_log.txt"

# ----- PROCESSING SETTINGS -----
# These settings control how the videos are processed. Adjust as needed.

# Reprocess mode (Boolean): If true, any existing stitched videos will be
# overwritten. Otherwise, skips folders where the output file already exists.
# Defaults to false.
reprocess: false

# Diagnostic mode (Boolean): If true, prints the video cut times to the console
# and embeds a timestamp into the video. Defaults to false.
diagnostic_mode: false

# Clear log (Boolean): If true, clears the log file at the start of each run.
# Otherwise, appends to the existing log. Defaults to false.
clear_log: false

# GPU (Boolean): Whether to use GPU acceleration (requires compatible ffmpeg
# build and GPU) Defaults to false.
use_gpu: false


# ----- VIDEO PROCESSING UTILITIES (OPTIONAL) -----
# These should not need to be changed unless you have multiple copies of FFmpeg
# installed and want to use a specific version.
ffmpeg_path: "ffmpeg/bin/ffmpeg.exe"
ffprobe_path: "ffmpeg/bin/ffprobe.exe"